name: task_movies
description: A new Flutter project.6
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  #flutter_native_splash: ^2.2.19
  introduction_screen: ^3.1.4
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  http: ^0.13.5
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.1
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.20
  glassmorphism: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/mask/
    - assets/movie-posters/
    - assets/svg/
    - assets/icons/
